Create model and controler witch save user
odanilodev/schedule-new pull request #12
Opened 2023-01-04 15:30 UTC by ovitindev

2023-01-04 15:57 UTC, odanilodev requested changes

2023-01-04 15:57 UTC, odanilodev commented on app/Http/Controllers/UserController.php
> +    public function store(Request $request)
Validar os dados 
segue video de como fazer 
https://www.youtube.com/watch?v=S_6MfLGMdbI

2023-01-04 15:57 UTC, odanilodev commented on app/Models/User.php
> +class User extends Model
Por segurança vc precisa usar o protected $fillable que funciona como se fosse uma lista branca ... onde ele só permite salvar no banco o que vc definir nesse array .. segue exemplo abaixo e video para aprender mais sobre

protected $fillable = [
        'name',
        'user_id',
        ..
        ..
        ..
    ];

assiste esse video .. é mto importante
https://www.youtube.com/watch?v=XUxk1FLRymI&t=10s

2023-01-05 12:33 UTC, odanilodev requested changes

2023-01-05 12:33 UTC, odanilodev commented on app/Http/Requests/LoginUser.php
> +            'birthday' => ['required'],
birthday precisa colocar uma validação de data

2023-01-10 20:25 UTC, oluisfelipedev approved these changes

2023-01-10 20:27 UTC, odanilodev approved these changes

2023-01-10 20:27 UTC, merged